

<?php
include('database.php');


// Check if report_id is set
if(isset($_REQUEST['report_id'])) {
    $report_id = $_REQUEST['report_id'];
   
    // Prepare and execute SELECT statement to retrieve report details
    $stmt = $connection->prepare("SELECT * FROM reports WHERE report_id = ?");
    $stmt->bind_param("i", $report_id);
    $stmt->execute();
    $result = $stmt->get_result();
   
    if($result->num_rows > 0) {
        $row = $result->fetch_assoc();
        $report_id = $row['report_id'];
        $report_name = $row['report_name'];
        $report_type = $row['report_type'];
        $report_date = $row['report_date'];
        $generated_by = $row['generated_by'];
        $description = $row['description'];
        $attachment_path = $row['attachment_path'];
    } else {
        echo "Report not found.";
    }
}

?>

<html>
<body>
    <form method="POST">
        <label for="report_id">Report ID:</label>
        <input type="number" name="report_id" value="<?php echo isset($report_id) ? $report_id : ''; ?>">
        <br><br>

        <label for="report_name">Report Name:</label>
        <input type="text" name="report_name" value="<?php echo isset($report_name) ? $report_name : ''; ?>">
        <br><br>

        <label for="report_type">Report Type:</label>
        <input type="text" name="report_type" value="<?php echo isset($report_type) ? $report_type : ''; ?>">
        <br><br>
       
        <label for="report_date">Report Date:</label>
        <input type="date" name="report_date" value="<?php echo isset($report_date) ? $report_date : ''; ?>">
        <br><br>
       
        <label for="generated_by">Generated By:</label>
        <input type="text" name="generated_by" value="<?php echo isset($generated_by) ? $generated_by : ''; ?>">
        <br><br>
        
        <label for="description">Description:</label>
        <input type="text" name="description" value="<?php echo isset($description) ? $description : ''; ?>">
        <br><br>
       
        <label for="attachment_path">Attachment Path:</label>
        <input type="text" name="attachment_path" value="<?php echo isset($attachment_path) ? $attachment_path : ''; ?>">
        <br><br>
       
        <input type="submit" name="up" value="Update">
       
    </form>
</body>
</html>

<?php
if(isset($_POST['up'])) {
    // Retrieve updated values from form
    $report_id = $_POST['report_id'];
    $report_name = $_POST['report_name'];
    $report_type = $_POST['report_type'];
    $report_date = $_POST['report_date'];
    $generated_by = $_POST['generated_by'];
    $description = $_POST['description'];
    $attachment_path = $_POST['attachment_path'];

    // Update the report in the database
    $stmt = $connection->prepare("UPDATE reports SET report_name=?, report_type=?, report_date=?, generated_by=?, description=?, attachment_path=? WHERE report_id=?");
    $stmt->bind_param("ssssssi", $report_name, $report_type, $report_date, $generated_by, $description, $attachment_path, $report_id);
   
    if ($stmt->execute()) {
        // Redirect to report.php after successful update
        header('Location: report.php');
        exit();
    } else {
        echo "Error updating report: " . $stmt->error;
    }
}
?>
